# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yuansmac/midi-to-hex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yuansmac/midi-to-hex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yuansmac/midi-to-hex/CMakeFiles /Users/yuansmac/midi-to-hex/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yuansmac/midi-to-hex/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named midi-to-hex

# Build rule for target.
midi-to-hex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midi-to-hex
.PHONY : midi-to-hex

# fast build rule for target.
midi-to-hex/fast:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/build
.PHONY : midi-to-hex/fast

Intel-HEX-Class/intelhex_class/intelhexclass.o: Intel-HEX-Class/intelhex_class/intelhexclass.cpp.o

.PHONY : Intel-HEX-Class/intelhex_class/intelhexclass.o

# target to build an object file
Intel-HEX-Class/intelhex_class/intelhexclass.cpp.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/Intel-HEX-Class/intelhex_class/intelhexclass.cpp.o
.PHONY : Intel-HEX-Class/intelhex_class/intelhexclass.cpp.o

Intel-HEX-Class/intelhex_class/intelhexclass.i: Intel-HEX-Class/intelhex_class/intelhexclass.cpp.i

.PHONY : Intel-HEX-Class/intelhex_class/intelhexclass.i

# target to preprocess a source file
Intel-HEX-Class/intelhex_class/intelhexclass.cpp.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/Intel-HEX-Class/intelhex_class/intelhexclass.cpp.i
.PHONY : Intel-HEX-Class/intelhex_class/intelhexclass.cpp.i

Intel-HEX-Class/intelhex_class/intelhexclass.s: Intel-HEX-Class/intelhex_class/intelhexclass.cpp.s

.PHONY : Intel-HEX-Class/intelhex_class/intelhexclass.s

# target to generate assembly for a file
Intel-HEX-Class/intelhex_class/intelhexclass.cpp.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/Intel-HEX-Class/intelhex_class/intelhexclass.cpp.s
.PHONY : Intel-HEX-Class/intelhex_class/intelhexclass.cpp.s

micronucleus_tool/library/littleWire_util.o: micronucleus_tool/library/littleWire_util.c.o

.PHONY : micronucleus_tool/library/littleWire_util.o

# target to build an object file
micronucleus_tool/library/littleWire_util.c.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/micronucleus_tool/library/littleWire_util.c.o
.PHONY : micronucleus_tool/library/littleWire_util.c.o

micronucleus_tool/library/littleWire_util.i: micronucleus_tool/library/littleWire_util.c.i

.PHONY : micronucleus_tool/library/littleWire_util.i

# target to preprocess a source file
micronucleus_tool/library/littleWire_util.c.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/micronucleus_tool/library/littleWire_util.c.i
.PHONY : micronucleus_tool/library/littleWire_util.c.i

micronucleus_tool/library/littleWire_util.s: micronucleus_tool/library/littleWire_util.c.s

.PHONY : micronucleus_tool/library/littleWire_util.s

# target to generate assembly for a file
micronucleus_tool/library/littleWire_util.c.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/micronucleus_tool/library/littleWire_util.c.s
.PHONY : micronucleus_tool/library/littleWire_util.c.s

micronucleus_tool/library/micronucleus_lib.o: micronucleus_tool/library/micronucleus_lib.c.o

.PHONY : micronucleus_tool/library/micronucleus_lib.o

# target to build an object file
micronucleus_tool/library/micronucleus_lib.c.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/micronucleus_tool/library/micronucleus_lib.c.o
.PHONY : micronucleus_tool/library/micronucleus_lib.c.o

micronucleus_tool/library/micronucleus_lib.i: micronucleus_tool/library/micronucleus_lib.c.i

.PHONY : micronucleus_tool/library/micronucleus_lib.i

# target to preprocess a source file
micronucleus_tool/library/micronucleus_lib.c.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/micronucleus_tool/library/micronucleus_lib.c.i
.PHONY : micronucleus_tool/library/micronucleus_lib.c.i

micronucleus_tool/library/micronucleus_lib.s: micronucleus_tool/library/micronucleus_lib.c.s

.PHONY : micronucleus_tool/library/micronucleus_lib.s

# target to generate assembly for a file
micronucleus_tool/library/micronucleus_lib.c.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/micronucleus_tool/library/micronucleus_lib.c.s
.PHONY : micronucleus_tool/library/micronucleus_lib.c.s

micronucleus_tool/micronucleus.o: micronucleus_tool/micronucleus.c.o

.PHONY : micronucleus_tool/micronucleus.o

# target to build an object file
micronucleus_tool/micronucleus.c.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/micronucleus_tool/micronucleus.c.o
.PHONY : micronucleus_tool/micronucleus.c.o

micronucleus_tool/micronucleus.i: micronucleus_tool/micronucleus.c.i

.PHONY : micronucleus_tool/micronucleus.i

# target to preprocess a source file
micronucleus_tool/micronucleus.c.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/micronucleus_tool/micronucleus.c.i
.PHONY : micronucleus_tool/micronucleus.c.i

micronucleus_tool/micronucleus.s: micronucleus_tool/micronucleus.c.s

.PHONY : micronucleus_tool/micronucleus.s

# target to generate assembly for a file
micronucleus_tool/micronucleus.c.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/micronucleus_tool/micronucleus.c.s
.PHONY : micronucleus_tool/micronucleus.c.s

midi-to-hex.o: midi-to-hex.cpp.o

.PHONY : midi-to-hex.o

# target to build an object file
midi-to-hex.cpp.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midi-to-hex.cpp.o
.PHONY : midi-to-hex.cpp.o

midi-to-hex.i: midi-to-hex.cpp.i

.PHONY : midi-to-hex.i

# target to preprocess a source file
midi-to-hex.cpp.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midi-to-hex.cpp.i
.PHONY : midi-to-hex.cpp.i

midi-to-hex.s: midi-to-hex.cpp.s

.PHONY : midi-to-hex.s

# target to generate assembly for a file
midi-to-hex.cpp.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midi-to-hex.cpp.s
.PHONY : midi-to-hex.cpp.s

midifile/src-library/Binasc.o: midifile/src-library/Binasc.cpp.o

.PHONY : midifile/src-library/Binasc.o

# target to build an object file
midifile/src-library/Binasc.cpp.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/Binasc.cpp.o
.PHONY : midifile/src-library/Binasc.cpp.o

midifile/src-library/Binasc.i: midifile/src-library/Binasc.cpp.i

.PHONY : midifile/src-library/Binasc.i

# target to preprocess a source file
midifile/src-library/Binasc.cpp.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/Binasc.cpp.i
.PHONY : midifile/src-library/Binasc.cpp.i

midifile/src-library/Binasc.s: midifile/src-library/Binasc.cpp.s

.PHONY : midifile/src-library/Binasc.s

# target to generate assembly for a file
midifile/src-library/Binasc.cpp.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/Binasc.cpp.s
.PHONY : midifile/src-library/Binasc.cpp.s

midifile/src-library/MidiEvent.o: midifile/src-library/MidiEvent.cpp.o

.PHONY : midifile/src-library/MidiEvent.o

# target to build an object file
midifile/src-library/MidiEvent.cpp.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiEvent.cpp.o
.PHONY : midifile/src-library/MidiEvent.cpp.o

midifile/src-library/MidiEvent.i: midifile/src-library/MidiEvent.cpp.i

.PHONY : midifile/src-library/MidiEvent.i

# target to preprocess a source file
midifile/src-library/MidiEvent.cpp.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiEvent.cpp.i
.PHONY : midifile/src-library/MidiEvent.cpp.i

midifile/src-library/MidiEvent.s: midifile/src-library/MidiEvent.cpp.s

.PHONY : midifile/src-library/MidiEvent.s

# target to generate assembly for a file
midifile/src-library/MidiEvent.cpp.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiEvent.cpp.s
.PHONY : midifile/src-library/MidiEvent.cpp.s

midifile/src-library/MidiEventList.o: midifile/src-library/MidiEventList.cpp.o

.PHONY : midifile/src-library/MidiEventList.o

# target to build an object file
midifile/src-library/MidiEventList.cpp.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiEventList.cpp.o
.PHONY : midifile/src-library/MidiEventList.cpp.o

midifile/src-library/MidiEventList.i: midifile/src-library/MidiEventList.cpp.i

.PHONY : midifile/src-library/MidiEventList.i

# target to preprocess a source file
midifile/src-library/MidiEventList.cpp.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiEventList.cpp.i
.PHONY : midifile/src-library/MidiEventList.cpp.i

midifile/src-library/MidiEventList.s: midifile/src-library/MidiEventList.cpp.s

.PHONY : midifile/src-library/MidiEventList.s

# target to generate assembly for a file
midifile/src-library/MidiEventList.cpp.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiEventList.cpp.s
.PHONY : midifile/src-library/MidiEventList.cpp.s

midifile/src-library/MidiFile.o: midifile/src-library/MidiFile.cpp.o

.PHONY : midifile/src-library/MidiFile.o

# target to build an object file
midifile/src-library/MidiFile.cpp.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiFile.cpp.o
.PHONY : midifile/src-library/MidiFile.cpp.o

midifile/src-library/MidiFile.i: midifile/src-library/MidiFile.cpp.i

.PHONY : midifile/src-library/MidiFile.i

# target to preprocess a source file
midifile/src-library/MidiFile.cpp.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiFile.cpp.i
.PHONY : midifile/src-library/MidiFile.cpp.i

midifile/src-library/MidiFile.s: midifile/src-library/MidiFile.cpp.s

.PHONY : midifile/src-library/MidiFile.s

# target to generate assembly for a file
midifile/src-library/MidiFile.cpp.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiFile.cpp.s
.PHONY : midifile/src-library/MidiFile.cpp.s

midifile/src-library/MidiMessage.o: midifile/src-library/MidiMessage.cpp.o

.PHONY : midifile/src-library/MidiMessage.o

# target to build an object file
midifile/src-library/MidiMessage.cpp.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiMessage.cpp.o
.PHONY : midifile/src-library/MidiMessage.cpp.o

midifile/src-library/MidiMessage.i: midifile/src-library/MidiMessage.cpp.i

.PHONY : midifile/src-library/MidiMessage.i

# target to preprocess a source file
midifile/src-library/MidiMessage.cpp.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiMessage.cpp.i
.PHONY : midifile/src-library/MidiMessage.cpp.i

midifile/src-library/MidiMessage.s: midifile/src-library/MidiMessage.cpp.s

.PHONY : midifile/src-library/MidiMessage.s

# target to generate assembly for a file
midifile/src-library/MidiMessage.cpp.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/MidiMessage.cpp.s
.PHONY : midifile/src-library/MidiMessage.cpp.s

midifile/src-library/Options.o: midifile/src-library/Options.cpp.o

.PHONY : midifile/src-library/Options.o

# target to build an object file
midifile/src-library/Options.cpp.o:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/Options.cpp.o
.PHONY : midifile/src-library/Options.cpp.o

midifile/src-library/Options.i: midifile/src-library/Options.cpp.i

.PHONY : midifile/src-library/Options.i

# target to preprocess a source file
midifile/src-library/Options.cpp.i:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/Options.cpp.i
.PHONY : midifile/src-library/Options.cpp.i

midifile/src-library/Options.s: midifile/src-library/Options.cpp.s

.PHONY : midifile/src-library/Options.s

# target to generate assembly for a file
midifile/src-library/Options.cpp.s:
	$(MAKE) -f CMakeFiles/midi-to-hex.dir/build.make CMakeFiles/midi-to-hex.dir/midifile/src-library/Options.cpp.s
.PHONY : midifile/src-library/Options.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... midi-to-hex"
	@echo "... Intel-HEX-Class/intelhex_class/intelhexclass.o"
	@echo "... Intel-HEX-Class/intelhex_class/intelhexclass.i"
	@echo "... Intel-HEX-Class/intelhex_class/intelhexclass.s"
	@echo "... micronucleus_tool/library/littleWire_util.o"
	@echo "... micronucleus_tool/library/littleWire_util.i"
	@echo "... micronucleus_tool/library/littleWire_util.s"
	@echo "... micronucleus_tool/library/micronucleus_lib.o"
	@echo "... micronucleus_tool/library/micronucleus_lib.i"
	@echo "... micronucleus_tool/library/micronucleus_lib.s"
	@echo "... micronucleus_tool/micronucleus.o"
	@echo "... micronucleus_tool/micronucleus.i"
	@echo "... micronucleus_tool/micronucleus.s"
	@echo "... midi-to-hex.o"
	@echo "... midi-to-hex.i"
	@echo "... midi-to-hex.s"
	@echo "... midifile/src-library/Binasc.o"
	@echo "... midifile/src-library/Binasc.i"
	@echo "... midifile/src-library/Binasc.s"
	@echo "... midifile/src-library/MidiEvent.o"
	@echo "... midifile/src-library/MidiEvent.i"
	@echo "... midifile/src-library/MidiEvent.s"
	@echo "... midifile/src-library/MidiEventList.o"
	@echo "... midifile/src-library/MidiEventList.i"
	@echo "... midifile/src-library/MidiEventList.s"
	@echo "... midifile/src-library/MidiFile.o"
	@echo "... midifile/src-library/MidiFile.i"
	@echo "... midifile/src-library/MidiFile.s"
	@echo "... midifile/src-library/MidiMessage.o"
	@echo "... midifile/src-library/MidiMessage.i"
	@echo "... midifile/src-library/MidiMessage.s"
	@echo "... midifile/src-library/Options.o"
	@echo "... midifile/src-library/Options.i"
	@echo "... midifile/src-library/Options.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

